### ISSUE TITLE
Problem with "Refresh all"

### ISSUE THREAD

**Issue by jsmorley** [NighthawkSLO/Mouse.dll#2]
NightHawkSLO, one thing I notice is that when the plugin is running, when your example skin is active for instance, doing a "Refresh all" of Rainmeter will cause huge problems. The mouse gets incredibly laggy and hard to control. I suspect that you are not properly closing and cleaning up your plugin when the skin in question is reloaded due to a refresh, and that is creating some kind of conflict or duplication of effort. 

This does not happen when the individual skin is refreshed, but is certain to happen with a "Refresh all".

**Comment by NighthawkSLO** [comment]
Fixed in the latest release, was due to deadlock - waiting for rainmeter to respond while rainmeter is waiting for the plugin to close
